#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : polkit-qt
Version  : 1.0.112.0
Release  : 3
URL      : https://download.kde.org/stable/apps/KDE4.x/admin/polkit-qt-1-0.112.0.tar.bz2
Source0  : https://download.kde.org/stable/apps/KDE4.x/admin/polkit-qt-1-0.112.0.tar.bz2
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: polkit-qt-lib = %{version}-%{release}
Requires: polkit-qt-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules pkgconfig(glib-2.0)
BuildRequires : pkg-config
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gobject-2.0)
BuildRequires : pkgconfig(polkit-agent-1)
BuildRequires : pkgconfig(polkit-gobject-1)
BuildRequires : qtbase-dev mesa-dev

%description
Polkit-qt
========
What is Polkit-qt?
------------------
Polkit-qt is a library that lets developers use the PolicyKit API through a nice
Qt-styled API. It is mainly a wrapper around QAction and QAbstractButton that
lets you integrate those two component easily with PolicyKit

%package dev
Summary: dev components for the polkit-qt package.
Group: Development
Requires: polkit-qt-lib = %{version}-%{release}
Provides: polkit-qt-devel = %{version}-%{release}
Requires: polkit-qt = %{version}-%{release}

%description dev
dev components for the polkit-qt package.


%package lib
Summary: lib components for the polkit-qt package.
Group: Libraries
Requires: polkit-qt-license = %{version}-%{release}

%description lib
lib components for the polkit-qt package.


%package license
Summary: license components for the polkit-qt package.
Group: Default

%description license
license components for the polkit-qt package.


%prep
%setup -q -n polkit-qt-1-0.112.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1555346493
mkdir -p clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1555346493
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/polkit-qt
cp COPYING %{buildroot}/usr/share/package-licenses/polkit-qt/COPYING
cp examples/COPYING %{buildroot}/usr/share/package-licenses/polkit-qt/examples_COPYING
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/polkit-qt5-1/PolkitQt1/ActionDescription
/usr/include/polkit-qt5-1/PolkitQt1/Agent/Listener
/usr/include/polkit-qt5-1/PolkitQt1/Agent/Session
/usr/include/polkit-qt5-1/PolkitQt1/Authority
/usr/include/polkit-qt5-1/PolkitQt1/Details
/usr/include/polkit-qt5-1/PolkitQt1/Gui/Action
/usr/include/polkit-qt5-1/PolkitQt1/Gui/ActionButton
/usr/include/polkit-qt5-1/PolkitQt1/Gui/ActionButtons
/usr/include/polkit-qt5-1/PolkitQt1/Identity
/usr/include/polkit-qt5-1/PolkitQt1/Subject
/usr/include/polkit-qt5-1/PolkitQt1/TemporaryAuthorization
/usr/include/polkit-qt5-1/polkitqt1-actiondescription.h
/usr/include/polkit-qt5-1/polkitqt1-agent-listener.h
/usr/include/polkit-qt5-1/polkitqt1-agent-session.h
/usr/include/polkit-qt5-1/polkitqt1-authority.h
/usr/include/polkit-qt5-1/polkitqt1-details.h
/usr/include/polkit-qt5-1/polkitqt1-export.h
/usr/include/polkit-qt5-1/polkitqt1-gui-action.h
/usr/include/polkit-qt5-1/polkitqt1-gui-actionbutton.h
/usr/include/polkit-qt5-1/polkitqt1-gui-actionbuttons.h
/usr/include/polkit-qt5-1/polkitqt1-identity.h
/usr/include/polkit-qt5-1/polkitqt1-subject.h
/usr/include/polkit-qt5-1/polkitqt1-temporaryauthorization.h
/usr/include/polkit-qt5-1/polkitqt1-version.h
/usr/lib64/cmake/PolkitQt5-1/PolkitQt5-1Config.cmake
/usr/lib64/cmake/PolkitQt5-1/PolkitQt5-1ConfigVersion.cmake
/usr/lib64/cmake/PolkitQt5-1/PolkitQt5-1Targets-relwithdebinfo.cmake
/usr/lib64/cmake/PolkitQt5-1/PolkitQt5-1Targets.cmake
/usr/lib64/libpolkit-qt5-agent-1.so
/usr/lib64/libpolkit-qt5-core-1.so
/usr/lib64/libpolkit-qt5-gui-1.so
/usr/lib64/pkgconfig/polkit-qt5-1.pc
/usr/lib64/pkgconfig/polkit-qt5-agent-1.pc
/usr/lib64/pkgconfig/polkit-qt5-core-1.pc
/usr/lib64/pkgconfig/polkit-qt5-gui-1.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libpolkit-qt5-agent-1.so.1
/usr/lib64/libpolkit-qt5-agent-1.so.1.112.0
/usr/lib64/libpolkit-qt5-core-1.so.1
/usr/lib64/libpolkit-qt5-core-1.so.1.112.0
/usr/lib64/libpolkit-qt5-gui-1.so.1
/usr/lib64/libpolkit-qt5-gui-1.so.1.112.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/polkit-qt/COPYING
/usr/share/package-licenses/polkit-qt/examples_COPYING
